[package]
name = "web-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
axum = "0.7.5"
git2 = "0.19.0"
[dev-dependencies]
anyhow = "1.0.87"
